### ISSUE TITLE
Can't install from OPAM

### ISSUE THREAD

**Issue by Richard-Degenne** [ocsigen/ocsigen-widgets#11]
Hi there,

I'm trying to get started with Eliom, and I'm having trouble installing `ocsigen-widgets`.

Here is what I tried:

    $ opam pin ocsigen-widgets https://github.com/ocsigen/ocsigen-widgets.git
    $ opam install ocsigen-widgets

But it resulted in:

    The following dependencies couldn't be met:
      - ocsigen-widgets -> ocsigen-toolkit -> js_of_ocaml > 2.7
    Your request can't be satisfied:
      - No package matches js_of_ocaml>2.7.

But `2.7` seems to be the latest available version of `js_of_ocaml`. I tried pinning `js_of_ocaml` too, but this resulted in the following.

    The following dependencies couldn't be met:
      - ocsigen-widgets -> ojquery -> js_of_ocaml < 2.4
    Your request can't be satisfied:
      - js_of_ocaml<2.4 is not available because your system doesn't comply with ocaml-version <= "4.01.0".

**Comment by vasilisp** [comment]
You also need to pin `ojquery` and `ocsigen-toolkit`.

**Comment by Richard-Degenne** [comment]
Yep, did the trick. Thanks.
