### ISSUE TITLE
Can't build the master branch

### ISSUE THREAD

**Issue by laheadle** [ocsigen/ocsigen-widgets#3]
running "make", eventually gives me:

eliomc -c -package text, -package magick -I _server/src/ -I _server/src/bindings/ -I _server/src/experimental/ -I _server/src/mobile/ -I _server/src/tools/ -I _server/src/widgets/  src/ow_pervasives.eliom
File "src/ow_pervasives.eliom", line 1:
Error: Could not find the .cmi file for interface src/ow_pervasives.eliomi.
make: *** [_server/src/ow_pervasives.cmo] Error 2

**Comment by laheadle** [comment]
did a make clean;make and got a little farther. Now I'm getting:

File "src/widgets/ow_active_set.eliom", line 71, characters 26-32:
Error: This expression has type (#item as 'a) Js.t -> unit
       but an expression was expected of type 'a Js.t -> 'b -> 'c
       Type unit is not compatible with type 'b -> 'c 
make: *** [_client/src/widgets/ow_active_set.cmo] Error 2

**Comment by balat** [comment]
Hi,
Are you using dev version of js_of_ocaml? I recommend to use opam to
install everything.
Be careful: Ocsigen-widgets is still very experimental and has currently no
maintainer. Large parts of the code will change in the future.
If you are installing it as a dependency to eliom-base-app, note that
eliom-base-app now depends of branch sharedreact of eliom (which is going
to become master quite soon). "opam pin" should help you to get the right
versions.
Vincent

Le Sun Feb 08 2015 at 05:33:36, Lyn Headley <notifications@github.com> a
écrit :
